### ISSUE TITLE
korsokolbuszowskie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15724]
artykuł znika : https://www.korsokolbuszowskie.pl/wiadomosci/4333,twoje-radio-cmolas-juz-od-dluzszego-czasu-przestalo-nadawac-swoje-audycje-sluchacze-zastanawiaja-sie-co-jest-przyczyna-tak-dlugiej-przerwy

**Comment by hawkeye116477** [comment]
@MajkiIT Nie widzę :cookie: , a nawet i po wyłączeniu IDCAC i PLRC, nadal artykuł robi manewr ninja.

**Comment by krystian3w** [comment]
```
korsokolbuszowskie.pl###popModal2
korsokolbuszowskie.pl##.modal-backdrop
korsokolbuszowskie.pl##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
korsokolbuszowskie.pl##body.modal-open header, body.modal-open .section.container, body.modal-open footer#footer, body.modal-open .bgad:style(z-index: auto !important;)

```

bugi robi to:

```css
body.modal-open header,
body.modal-open .section.container,
body.modal-open footer#footer,
body.modal-open .bgad {
 z-index:auto
}
```
Za wysoko dali albo kij wie...
