### ISSUE TITLE
tekstowo.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20378]
Zalogowani mają teledyski dużo większe:

`https://www.tekstowo.pl/piosenka,marie,zero_calorie_cookie.html`

```css
tekstowo.pl#@##advSong
tekstowo.pl#$##advSong { visibility: hidden !important }
tekstowo.pl#@#[class^="adv-"]
tekstowo.pl#$#.teledysk { flex: 0 0 100% !important; max-width: 100% !important; }
```

W uBo i AG można to poprawić.
