### ISSUE TITLE
ppe.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20619]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Linux

### Przeglądarka internetowa (Web browser)

Vivaldi 5.0.2497.38 (Chromium 96.0.4664.137)

### Bloker (Blocker)

uBlock Origin 1.40.8

### Używane listy filtrów (Used filter lists)

```
 added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 32896-6, now
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 99855-106, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 20943-51, now
    https://www.i-dont-care-about-cookies.eu/abp/: 24163-141, now

 default: 
    POL-0: 7753-17, now
    POL-2: 1263-11, now
    easylist: 63067-3259, now
    easyprivacy: 26627-23, now
    plowe-0: 3682-836, now
    ublock-abuse: 76-0, now
    ublock-badware: 3724-886, now
    ublock-filters: 30159-278, now
    ublock-privacy: 190-3, now
    ublock-unbreak: 1682-40, now
    urlhaus-1: 8471-24, now
```

### Inne rozszerzenia (Other extensions)

Polska Ciasteczkowa Zgoda 1.45.0

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

PPE zaktualizowali do wersji 4.0 i od razu pojawiły się puste pola po reklamach.
Prawdopodobnie wystarczy jedynie dodać `ppe.pl##div[class^="banner-placeholder"], .banner-screening`.

![2022-01-17_13-31](https://user-images.githubusercontent.com/19818572/149770001-eed4ae41-adf0-453c-8f87-306647e64023.png)
![2022-01-17_13-31_1](https://user-images.githubusercontent.com/19818572/149770034-6d24732a-e418-4a18-b6de-53a54edbb184.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
