### ISSUE TITLE
forum.android.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20708]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://forum.android.com.pl/topic/257587-magic-earth-navigation-maps
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 5.1.2567.39 (Stable channel) stable (64-bit) 

### Bloker (Blocker)

uBlock Origin 1.41.2

### Używane listy filtrów (Used filter lists)

```
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 33038-9, 23h.7m
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 115285-110, 23h.7m
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 21076-42, 23h.7m
    https://www.i-dont-care-about-cookies.eu/abp/: 24361-140, 23h.7m
    ublock-annoyances: 4402-18, 23h.7m
  default: 
    user-filters: 0-0, never
    POL-0: 7768-17, 23h.7m
    POL-2: 1273-14, 23h.7m
    easylist: 63622-2817, 23h.7m
    easyprivacy: 26560-126, now
    plowe-0: 3675-825, 23h.7m
    ublock-abuse: 77-0, 23h.7m
    ublock-badware: 3965-912, 23h.7m
    ublock-filters: 30227-260, 23h.7m
    ublock-privacy: 201-2, 23h.7m
    ublock-unbreak: 1716-40, 23h.7m
    urlhaus-1: 6525-9, 23h.7m
```

### Inne rozszerzenia (Other extensions)

Polska Ciasteczkowa Zgoda 1.45.1

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Reklama autozamykająca się, wyświetla się chyba tylko 1 raz, ale wraca po zjedzeniu ciasteczek.

![2022-02-15_21-53](https://user-images.githubusercontent.com/19818572/154148018-880e6dc3-cc10-43af-8cd6-592fbdb32b85.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
