### ISSUE TITLE
kalendarzswiatnietypowych.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20723]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 5.1.2567.46 (Stable channel) stable (64-bit)

### Bloker (Blocker)

uBlock Origin 1.41.8

### Używane listy filtrów (Used filter lists)

```
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 33018-10, 2h.2m
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 110505-105, 2h.1m
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 836-0, 2d.5h.33m
    https://raw.githubusercontent.com/FiltersHeroes/PolishSocialCookiesFiltersDev/master/adblock_social_filters/adblock_social_list.txt: 12272-0, 2h
    https://raw.githubusercontent.com/FiltersHeroes/PolishSocialCookiesFiltersDev/master/cookies_filters/adblock_cookies.txt: 9455-13, 1h.59m
    https://www.i-dont-care-about-cookies.eu/abp/: 24384-139, 2d.5h.33m
    fanboy-social: 23184-18, 2d.5h.33m
    ublock-annoyances: 4408-14, 2d.5h.33m
  default: 
    user-filters: 1-0, never
    POL-0: 7773-16, 1h.58m
    POL-2: 1273-14, 2h.3m
    easylist: 64083-2828, 2d.5h.33m
    easyprivacy: 26634-127, 2d.5h.33m
    plowe-0: 3673-823, 2d.5h.33m
    ublock-abuse: 72-0, 2d.5h.33m
    ublock-badware: 3899-928, 2d.5h.33m
    ublock-filters: 30228-277, 2d.5h.33m
    ublock-privacy: 204-9, 2d.5h.33m
    ublock-unbreak: 1720-40, 2d.5h.33m
    urlhaus-1: 8437-9, 1h.57m
```

### Inne rozszerzenia (Other extensions)

Polska Ciasteczkowa Zgoda 1.45.1

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![2022-03-04_16-41](https://user-images.githubusercontent.com/19818572/156794235-0c51ad2f-8965-49b6-a366-d38b35e95598.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
