### ISSUE TITLE
antyweb.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#21288]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://antyweb.pl/starlink-taniej-ale-z-limitem-pobierania-danych
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 5.4.2753.51

### Bloker (Blocker)

uBlock Origin 1.44.2

### Używane listy filtrów (Used filter lists)

```
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 41163-3, 5m
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 165954-111, 5m
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 22017-45, 5m
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 882-27, 5m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 13067-298, 1m
    https://www.i-dont-care-about-cookies.eu/abp/: 25366-145, 5m
    fanboy-social: 23354-22, 1m
    ublock-annoyances: 4821-12, 5m
  default: 
    user-filters: 0-0, never
    POL-0: 7852-22, 7m
    POL-2: 1276-14, 7m
    easylist: 63572-2416, 6m
    easyprivacy: 30603-1175, 6m
    plowe-0: 3673-879, 5m
    ublock-abuse: 76-0, 5m
    ublock-badware: 4200-938, 5m
    ublock-filters: 32778-216, 5m
    ublock-privacy: 245-8, 5m
    ublock-quick-fixes: 217-10, 5m
    ublock-unbreak: 1858-43, 5m
    urlhaus-1: 6793-1, 5m
```

### Inne rozszerzenia (Other extensions)

Polska Ciasteczkowa Zgoda 1.45.1

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Panie Zarządco, jest pełno dziur na pańskiej drodze, trzeba coś w tej sprawie zadziałać, bo może ktoś niedługo wpadnie i dopiero będzie problem :smile:.

![2022-09-18_22-01](https://user-images.githubusercontent.com/19818572/190926179-e1b714ba-de0a-42af-ba30-84290148a635.png)

![2022-09-18_22-01_1](https://user-images.githubusercontent.com/19818572/190926170-eb169b4a-c243-4e29-809f-032f9e209b01.png)

![2022-09-18_22-01_2](https://user-images.githubusercontent.com/19818572/190926176-f1d37549-9618-489f-a588-bc12e224acf0.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
