### ISSUE TITLE
pananimacja.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#21835]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 6.1.3035.75

### Bloker (Blocker)

uBlock Origin 1.50.0

### Używane listy filtrów (Used filter lists)

```
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 47135-624, 3m
  https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 373725-8, 3m
  https://raw.githubusercontent.com/FiltersHeroes/PolishSocialCookiesFiltersDev/master/cookies_filters/adblock_cookies.txt: 10104-16, 3m
  https://www.i-dont-care-about-cookies.eu/abp/: 25722-145, 3m
  adguard-generic: 71806-710, 3m
  ublock-annoyances: 5100-52, 3m
 default:
  user-filters: 2-0, never
  POL-0: 7962-21, 3m
  POL-2: 1275-14, 3m
  easylist: 66858-970, 3m
  easyprivacy: 30599-158, 3m
  plowe-0: 3735-972, 3m
  ublock-badware: 7533-862, 3m
  ublock-filters: 33559-3761, 3m
  ublock-privacy: 410-3, 3m
  ublock-quick-fixes: 225-25, 3m
  ublock-unbreak: 2049-92, 3m
  urlhaus-1: 6798-1, 3m
```

### Inne rozszerzenia (Other extensions)

Polska Ciasteczkowa Zgoda 1.45.1

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![2023-06-20_19-44](https://github.com/MajkiIT/polish-ads-filter/assets/19818572/8b692be4-905e-43cb-9dee-949bf8f18390)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
