### ISSUE TITLE
mito-pharma.pl

### ISSUE THREAD

**Issue by xparadoxical** [MajkiIT/polish-ads-filter#22631]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.mito-pharma.pl/Cynk-jak-go-prawidlowo-suplementowac-Wlasciwosci-objawy-niedoboru-i-nadmiaru-blog-pol-1645612419.html
https://www.mito-pharma.pl
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Opera GX 114.0.5282.248

### Bloker (Blocker)

uBlock Origin 1.60.0

### Używane listy filtrów (Used filter lists)

```
listset (total-discarded, last-updated):
 added:
  easylist-chat: 217-0, now
  easylist-newsletters: 8338-16, now
  easylist-notifications: 3467-6, now
 default:
  user-filters: 3-0, never
  POL-0: 8774-9, now
  POL-2: 1280-14, now
  easylist: 78067-499, 1h.24m Δ
  easyprivacy: 53301-709, 1h.24m Δ
  plowe-0: 3541-15, 11m
  ublock-badware: 12339-1, 1h.24m Δ
  ublock-filters: 40912-433, 1h.24m Δ
  ublock-privacy: 1617-22, 1h.24m Δ
  ublock-quick-fixes: 223-0, 1h.24m Δ
  ublock-unbreak: 2540-1, 1h.24m Δ
  urlhaus-1: 23630-0, now
```

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Najpierw jest pytanie od uBlocka czy w ogóle załadować stronę, a następnie wszystko poza html'em zostaje zablokowane przez ogólny filtr `||mito-pharma.pl^`. Strona główna z kolei w ogóle się nie ładuje (ERR_FAILED) chyba przez zablokowanego service workera. Po wyłączeniu uBlocka i załadowaniu strony można zobaczyć, że strona nie wygląda na taką do zablokowania w pełni.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))
