### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by userOperaFF** [MajkiIT/polish-ads-filter#4635]
Reklama Opery w dolnym rogu:

![obraz](https://user-images.githubusercontent.com/33114475/33287149-0967ff38-d3b8-11e7-95c0-041e52240a67.png)

---

Znając życie na Operze też ją wciskają 👍 

Reklama  ma różne id / data-toggle / class i jest różnym elementem html ( `<u>`,  `<small>`,  `<code>`, `<div>`) z tłem w css (base64). 

Stały ma tylko fragment CSS:

```css
LosowyUchwyt {
position: fixed;
bottom: 10px;
right: calc((100% - 980px) / 2 - 165px) !important;
display: block !important;
width: 160px !important;
height: 260px !important;
z-index: 1001 !important;
(...)
background-repeat: no-repeat;
cursor: pointer !important;
}
```

`(...)` - tła w base64
