### ISSUE TITLE
zycie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5234]
![2017-12-21 12_40_49-zycie podkarpackie - informacje z regionu przemysla jaroslawia lubaczowa prze](https://user-images.githubusercontent.com/5884000/34254408-3fe4d59e-e64c-11e7-854d-bf6331155eb8.png)
puste miejsce

![2017-12-21 12_42_01-zycie podkarpackie - informacje z regionu przemysla jaroslawia lubaczowa prze](https://user-images.githubusercontent.com/5884000/34254432-608aeb12-e64c-11e7-8f53-123105a762c1.png)
okładki

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by userOperaFF** [comment]
Na puste miejsca testowo: `##.images.left-dd > .advert-item`

![obraz](https://user-images.githubusercontent.com/33114475/34322426-6a2d5b50-e827-11e7-976b-26a3f75df96e.png)


Brak grafik robi jakiś taki CSS na podstawie filtrów uBlock: 

```css

A[target="_blank"] > IMG, #cookieView:not(body):not(html), DIV[style="padding: 5px 25px 5px 15px;"], DIV[style="border: 10px solid rgb(138, 138, 138); border-radius: 10px; box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.9); background-color: rgb(255, 255, 255); padding: 8px 8px 10px; position: fixed; z-index: 99999; right: 20px; left: 20px; bottom: 20px; width: 700px; max-width: 90%;"], [id^="polityka-prywatnosci"], [class^="kom_polityka_prywatnosci"], .cnil-banner__content, #policy-info, #notice_bar, #komunikat-cookies, #cokPyt, #adnp, .header-adblock, .widget-ads-content, [class*="cg-template"], #pixad-box, a[href*="://converti.se/click/"], .onnetwork-video, #LinkArea\:gry, .linkSponsorowany, .ppa-slot, #advertisments, .adform-slot, .ads, #widget-shop, .trizer-bnr, [class^="ad-"], [class*="reklama"], .ad, [class$="-ads"], [id^="crt-"], a[href*="://clicks.fortunaaffiliates.com/"], a[href*="techmaniak.pl/www/gact/ckk.php"], A[href*="k.tradedoubler.com/click"], ads-top-layer, A[href*="/emisja.contentstream.pl/_/ctr/"], IMG[alt="Reklama"], IMG[src^="http://www.audiostereo.pl/banery/"], IMG[title^="Sponsorowan"], TopTextAd, [class*="box-advert"], [class^="ADbox"], [class^="adSrodek"], [class^="sponsorowany"], [href*="://clickserve.dartsearch.net/link/click"], [href^="http://adserwer."], [href^="http://csr.onet.pl/eclk/clk"], [id$="reklamy"], [id*="-billboard-advert"], [id^="ad_global"], [id^="ad_iframe"], [id^="ads_"], [id^="aswift_"], [id^="banner_900x"], [id^="boxRegioPromoTab"], [id^="ceneoaffcontainer"], [id^="giercowniaAd"], [id^="nokaut_ads_category_"], [id^="pianoMediaBoxInfo"], [id^="slot_ad_billboard"], [id^="sponsorowany"], [id^="AdsDetailsTop"], a[href*="/ad/click/"], a[href*="adnow.com/click"], a[href*="bbelements.com/please/"], a[href="http://upfiles.net/ref/"], a[href="http://www.likeplus.eu/clickback"], [href^="http://advmanager.techfun.pl/redirect/"], [href^="http://delivery.clickonometrics.pl/campaign="], [href^="http://www.trizer.pl/?utm_source"], [href^="https://www.solutions4ad.com/partner/scripts/click.php"], [href^="https://ad.zanox.com/ppc/"], img[alt="reklama"], [id^="adv-"], [class^="adv-"], [id^="commentAd"], [class^="advertisement"], A[href$="/reklama"], [src*="/banners/banner"], [id*="reklama"], [href^="https://affiliate.bitbay.net/"], A[href*="beaffiliates.com/processing/clickthrgh.asp"], [href^="https://gamehag.com/r/"], [href^="http://affiliates.bet-at-home.com/processing/clickthrgh.asp"], a[href="http://www.livelooker.com"], ADS-RIGHT, AFS-AD, [ad-id^="googlead"], [lazy-ad="lefttop_banner"], [onclick^="window.open('http://adultfriendfinder.com/search/"], a[data-obtrack^="http://paid.outbrain.com/network/redir?"], a[data-oburl^="http://paid.outbrain.com/network/redir?"], a[data-oburl^="https://paid.outbrain.com/network/redir?"], a[data-redirect^="http://click.plista.com/pets"], a[data-redirect^="this.href='http://paid.outbrain.com/network/redir?"], a[data-url^="http://paid.outbrain.com/network/redir?"], a[data-widget-outbrain-redirect^="http://paid.outbrain.com/network/redir?"], a[href$="/vghd.shtml"], a[href*=".adk2x.com/"], a[href*=".qertewrt.com/"], a[href*="/adrotate-out.php?"], a[href*="/cmd.php?ad="], a[href*="=Adtracker"], a[href*="ad2upapp.com/"], a[href*="emprestimo.eu"], a[href*="googleme.eu"], a[href*="letsadvertisetogether.com"], a[href*="onclkds."], [href^=" http://ads.ad-center.com/"], [href^=" http://n47adshostnet.com/"], [href^="//adbit.co/?a=Advertise&"], [href^="//ads.ad-center.com/"], [href^="//api.ad-goi.com/"], [href^="//srv.buysellads.com/"], [href^="//t.MtagMonetizationA.com/"], [href^="//tracking.content-recommendation.net/"][href*="/sponsored/click.html?"], [href^="//www.mgid.com/"], [href^="http://1phads.com/"], [href^="http://360ads.go2cloud.org/"], [href^="http://3wr110.net/"], [href^="http://NowDownloadAll.com"], [href^="http://a.adquantix.com/"], [href^="http://abc2.mobile-10.com/"], [href^="http://ad-apac.doubleclick.net/"], [href^="http://ad-emea.doubleclick.net/"], [href^="http://ad.au.doubleclick.net/"], [href^="http://ad.doubleclick.net/"], [href^="http://ad.yieldmanager.com/"], [href^="http://adclick.g.doubleclick.net/"], [href^="http://adexprt.me/"], [href^="http://adf.ly/?id="], [href^="http://adfarm.mediaplex.com/"], [href^="http://adlev.neodatagroup.com/"], [href^="http://admingame.info/"], [href^="http://adprovider.adlure.net/"], [href^="http://adrunnr.com/"], [href^="http://ads.activtrades.com/"], [href^="http://ads.ad-center.com/"], [href^="http://ads.affbuzzads.com/"], [href^="http://ads.betfair.com/redirect.aspx?"], [href^="http://ads.expekt.com/affiliates/"], [href^="http://ads.integral-marketing.com/"], [href^="http://ads.pheedo.com/"], [href^="http://ads.sprintrade.com/"], [href^="http://adserver.adtech.de/"], [href^="http://adserver.adtechus.com/"], [href^="http://adserver.itsfogo.com/"], [href^="http://adserving.liveuniversenetwork.com/"], [href^="http://adserving.unibet.com/"], [href^="http://adsrv.keycaptcha.com"], [href^="http://adtrack123.pl/"], [href^="http://adtrackone.eu/"], [href^="http://adtransfer.net/"], [href^="http://adultfriendfinder.com/p/register.cgi?pid="], [href^="http://aff.ironsocket.com/"], [href^="http://affiliate.coral.co.uk/processing/"], [href^="http://affiliate.glbtracker.com/"], [href^="http://affiliate.godaddy.com/"], [href^="http://affiliates.pinnaclesports.com/processing/"], [href^="http://affiliates.score-affiliates.com/"], [href^="http://aflrm.com/"], [href^="http://anonymous-net.com/"], [href^="http://api.content.ad/"], [href^="http://api.ringtonematcher.com/"], [href^="http://at.atwola.com/"], [href^="http://b.bestcompleteusa.info/"], [href^="http://banners.victor.com/processing/"], [href^="http://bc.vc/?r="], [href^="http://bcp.crwdcntrl.net/"], [href^="http://bestorican.com/"], [href^="http://bluehost.com/track/"], [href^="http://bonusfapturbo.nmvsite.com/"], [href^="http://bs.serving-sys.com/"], [href^="http://buysellads.com/"], [href^="http://c.actiondesk.com/"], [href^="http://c.ketads.com/"], [href^="http://callville.xyz/"], [href^="http://campaign.bharatmatrimony.com/cbstrack/"], [href^="http://campaign.bharatmatrimony.com/track/"], [href^="http://casino-x.com/?partner"], [href^="http://cdn.adsrvmedia.net/"], [href^="http://cdn.adstract.com/"], [href^="http://cdn3.adbrau.com/"], [href^="http://cdn3.adexprts.com/"], [href^="http://centertrust.xyz/"], [href^="http://chaturbate.com/affiliates/"], [href^="http://cinema.friendscout24.de?"], [href^="http://click.guamwnvgashbkashawhgkhahshmashcas.pw/"], [href^="http://click.plista.com/pets"], [href^="http://clickandjoinyourgirl.com/"], [href^="http://clicks.binarypromos.com/"], [href^="http://clicks.guamwnvgashbkashawhgkhahshmashcas.pw/"], [href^="http://clickserv.sitescout.com/"], [href^="http://clk.directrev.com/"], [href^="http://clkmon.com/adServe/"], [href^="http://codec.codecm.com/"], [href^="http://connectlinking6.com/"], [href^="http://contractallsticker.net/"], [href^="http://cpaway.afftrack.com/"], [href^="http://d2.zedo.com/"], [href^="http://data.ad.yieldmanager.net/"], [href^="http://data.committeemenencyclopedicrepertory.info/"], [href^="http://data.linoleictanzaniatitanic.com/"], [href^="http://databass.info/"], [href^="http://ddownload39.club/"], [href^="http://dethao.com/"], [href^="http://dftrck.com/"], [href^="http://down1oads.com/"], [href^="http://download-performance.com/"], [href^="http://dwn.pushtraffic.net/"], [href^="http://easydownload4you.com/"], [href^="http://eclkmpsa.com/"], [href^="http://elite-sex-finder.com/?"], [href^="http://elitefuckbook.com/"], [href^="http://engine.newsmaxfeednetwork.com/"], [href^="http://farm.plista.com/pets"], [href^="http://feedads.g.doubleclick.net/"], [href^="http://fileloadr.com/"], [href^="http://fileupnow.rocks/"], [href^="http://finaljuyu.com/"], [href^="http://findersocket.com/"], [href^="http://freesoftwarelive.com/"], [href^="http://fsoft4down.com/"], [href^="http://fusionads.net"], [href^="http://galleries.pinballpublishernetwork.com/"], [href^="http://galleries.securewebsiteaccess.com/"], [href^="http://games.ucoz.ru/"][target="_blank"], [href^="http://gca.sh/user/register?ref="], [href^="http://get.slickvpn.com/"], [href^="http://getlinksinaseconds.com/"], [href^="http://go.ad2up.com/"], [href^="http://go.mobisla.com/"], [href^="http://go.oclaserver.com/"], [href^="http://go.seomojo.com/tracking202/"], [href^="http://goldmoney.com/?gmrefcode="], [href^="http://green.trafficinvest.com/"], [href^="http://greensmoke.com/"], [href^="http://guideways.info/"], [href^="http://hd-plugins.com/download/"], [href^="http://hdplugin.flashplayer-updates.com/"], [href^="http://hyperlinksecure.com/go/"], [href^="http://imads.integral-marketing.com/"], [href^="http://install.securewebsiteaccess.com/"], [href^="http://istri.it/?"], [href^="http://jobitem.org/"], [href^="http://join3.bannedsextapes.com/track/"], [href^="http://k2s.cc/pr/"], [href^="http://keep2share.cc/pr/"], [href^="http://landingpagegenius.com/"], [href^="http://latestdownloads.net/download.php?"], [href^="http://linksnappy.com/?ref="], [href^="http://liversely.com/"], [href^="http://liversely.net/"], [href^="http://lp.ezdownloadpro.info/"], [href^="http://lp.ilivid.com/"], [href^="http://lp.ncdownloader.com/"], [href^="http://marketgid.com"], [href^="http://media.paddypower.com/redirect.aspx?"], [href^="http://mgid.com/"], [href^="http://mmo123.co/"], [href^="http://mo8mwxi1.com/"], [href^="http://mojofun.info/"], [href^="http://n.admagnet.net/"], [href^="http://n217adserv.com/"], [href^="http://onclickads.net/"], [href^="http://online.ladbrokes.com/promoRedirect?"], [href^="http://paid.outbrain.com/network/redir?"], [href^="http://pan.adraccoon.com?"], [href^="http://papi.mynativeplatform.com:80/pub2/"], [href^="http://partner.sbaffiliates.com/"], [href^="http://pokershibes.com/index.php?ref="], [href^="http://prochina.link/"], [href^="http://prochina.space/"], [href^="http://promos.bwin.com/"], [href^="http://prousa.work/"], [href^="http://pubads.g.doubleclick.net/"], [href^="http://pwrads.net/"], [href^="http://record.betsafe.com/"], [href^="http://record.commissionking.com/"], [href^="http://record.sportsbetaffiliates.com.au/"], [href^="http://refer.webhostingbuzz.com/"], [href^="http://ryushare.com/affiliate.python"], [href^="http://searchtabnew.com/"], [href^="http://secure.hostgator.com/~affiliat/"], [href^="http://secure.signup-page.com/"], [href^="http://secure.signup-way.com/"], [href^="http://see-work.info/"], [href^="http://serve.williamhill.com/promoRedirect?"], [href^="http://server.cpmstar.com/click.aspx?poolid="], [href^="http://servicegetbook.net/"], [href^="http://sharesuper.info/"], [href^="http://srvpub.com/"], [href^="http://stateresolver.link/"], [href^="http://t.mdn2015x1.com/"], [href^="http://t.mdn2015x2.com/"], [href^="http://t.mdn2015x3.com/"], [href^="http://t.wowtrk.com/"], [href^="http://taboola-"][href*="/redirect.php?app.type="], [href^="http://tezfiles.com/pr/"], [href^="http://tour.affbuzzads.com/"], [href^="http://track.adform.net/"], [href^="http://track.incognitovpn.com/"], [href^="http://tracking.crazylead.com/"], [href^="http://tracking.deltamediallc.com/"], [href^="http://tracking.toroadvertising.com/"], [href^="http://ul.to/ref/"], [href^="http://uploaded.net/ref/"], [href^="http://us.marketgid.com"], [href^="http://web.adblade.com/"], [href^="http://websitedhoome.com/"], [href^="http://webtrackerplus.com/"], [href^="http://wgpartner.com/"], [href^="http://www.123-reg.co.uk/affiliate2.cgi"], [href^="http://www.1clickdownloader.com/"], [href^="http://www.1clickmoviedownloader.info/"], [href^="http://www.TwinPlan.com/AF_"], [href^="http://www.accuserveadsystem.com/accuserve-go.php?"], [href^="http://www.adbrite.com/mb/commerce/purchase_form.php?"], [href^="http://www.adshost2.com/"], [href^="http://www.adskeeper.co.uk/"], [href^="http://www.adxpansion.com"], [href^="http://www.affbuzzads.com/affiliate/"], [href^="http://www.affiliates1128.com/processing/"], [href^="http://www.amazon.co.uk/exec/obidos/external-search?"], [href^="http://www.babylon.com/welcome/index?affID"], [href^="http://www.badoink.com/go.php?"], [href^="http://www.bet365.com/"][href*="&affiliate="], [href^="http://www.bet365.com/"][href*="?affiliate="], [href^="http://www.bitlord.me/share/"], [href^="http://www.brightwheel.info/"], [href^="http://www.clickansave.net/"], [href^="http://www.clkads.com/adServe/"], [href^="http://www.dealcent.com/register.php?affid="], [href^="http://www.dl-provider.com/search/"], [href^="http://www.down1oads.com/"], [href^="http://www.download-provider.org/"], [href^="http://www.downloadplayer1.com/"], [href^="http://www.downloadthesefiles.com/"], [href^="http://www.downloadweb.org/"], [href^="http://www.drowle.com/"], [href^="http://www.easydownloadnow.com/"], [href^="http://www.epicgameads.com/"], [href^="http://www.faceporn.net/free?"], [href^="http://www.fbooksluts.com/"], [href^="http://www.firstclass-download.com/"], [href^="http://www.firstload.com/affiliate/"], [href^="http://www.firstload.de/affiliate/"], [href^="http://www.flashx.tv/downloadthis"], [href^="http://www.fleshlight.com/"], [href^="http://www.fonts.com/BannerScript/"], [href^="http://www.fpcTraffic2.com/blind/in.cgi?"], [href^="http://www.freefilesdownloader.com/"], [href^="http://www.friendlyadvertisements.com/"], [href^="http://www.friendlyquacks.com/"], [href^="http://www.gamebookers.com/cgi-bin/intro.cgi?"], [href^="http://www.getyourguide.com/?partner_id="], [href^="http://www.graboid.com/affiliates/"], [href^="http://www.greenmangaming.com/?tap_a="], [href^="http://www.idownloadplay.com/"], [href^="http://www.incredimail.com/?id="], [href^="http://www.installads.net/"], [href^="http://www.ireel.com/signup?ref"], [href^="http://www.linkbucks.com/referral/"], [href^="http://www.liutilities.com/"], [href^="http://www.liversely.net/"], [href^="http://www.menaon.com/installs/"], [href^="http://www.mobileandinternetadvertising.com/"], [href^="http://www.my-dirty-hobby.com/?sub="], [href^="http://www.myfreecams.com/?co_id="][href*="&track="], [href^="http://www.myfreepaysite.com/sfw.php?aid"], [href^="http://www.myfreepaysite.com/sfw_int.php?aid"], [href^="http://www.mysuperpharm.com/"], [href^="http://www.myvpn.pro/"], [href^="http://www.on2url.com/app/adtrack.asp"], [href^="http://www.paddypower.com/?AFF_ID="], [href^="http://www.pheedo.com/"], [href^="http://www.pinkvisualgames.com/?revid="], [href^="http://www.pinkvisualpad.com/?revid="], [href^="http://www.plus500.com/?id="], [href^="http://www.quick-torrent.com/download.html?aff"], [href^="http://www.revenuehits.com/"], [href^="http://www.ringtonematcher.com/"], [href^="http://www.roboform.com/php/land.php"], [href^="http://www.seekbang.com/cs/"], [href^="http://www.sex.com/?utm_"], [href^="http://www.sex.com/pics/?utm_"], [href^="http://www.sex.com/videos/?utm_"], [href^="http://www.sexgangsters.com/?pid="], [href^="http://www.sfippa.com/"], [href^="http://www.socialsex.com/"], [href^="http://www.streamate.com/exports/"], [href^="http://www.streamtunerhd.com/signup?"], [href^="http://www.terraclicks.com/"], [href^="http://www.text-link-ads.com/"], [href^="http://www.tirerack.com/affiliates/"], [href^="http://www.torntv-downloader.com/"], [href^="http://www.torntvdl.com/"], [href^="http://www.twinplan.com/AF_"], [href^="http://www.uniblue.com/cm/"], [href^="http://www.urmediazone.com/signup"], [href^="http://www.usearchmedia.com/signup?"], [href^="http://www.wantstraffic.com/"], [href^="http://www.webtrackerplus.com/"], [href^="http://www.xmediaserve.com/"], [href^="http://www.yourfuckbook.com/?"], [href^="http://www1.clickdownloader.com/"], [href^="http://www5.smartadserver.com/call/pubjumpi/"], [href^="http://wxdownloadmanager.com/dl/"], [href^="http://xads.zedo.com/"], [href^="http://xtgem.com/click?"], [href^="http://yads.zedo.com/"], [href^="http://z1.zedo.com/"], [href^="http://zevera.com/afi.html"], [href^="https://ad.atdmt.com/"], [href^="https://ad.doubleclick.net/"], [href^="https://adhealers.com/"], [href^="https://affiliates.bet-at-home.com/processing/"], [href^="https://atomidownload.com/"], [href^="https://bs.serving-sys.com"], [href^="https://chaturbate.com/affiliates/"], [href^="https://click.plista.com/pets"], [href^="https://dcs.adgear.com/clicks/"], [href^="https://dediseedbox.com/clients/aff.php?"], [href^="https://dltags.com/"], [href^="https://farm.plista.com/pets"], [href^="https://go.ad2up.com/"], [href^="https://keep2share.cc/pr/"], [href^="https://paid.outbrain.com/network/redir?"], [href^="https://pubads.g.doubleclick.net/"], [href^="https://secure.eveonline.com/ft/?aid="], [href^="https://torguard.net/aff.php"], [href^="https://tracking.truthfinder.com/?a="], [href^="https://trackjs.com/?utm_source"], [href^="https://trklvs.com/"], [href^="https://trust.zone/go/r.php?RID="], [href^="https://understandsolar.com/signup/?lead_source="][href*="&tracking_code="], [href^="https://windscribe.com/promo/"], [href^="https://www.adskeeper.co.uk/"], [href^="https://www.camyou.com/?cam="][href*="&track="], [href^="https://www.dsct1.com/"], [href^="https://www.firstload.com/affiliate/"], [href^="https://www.googleadservices.com/pagead/aclk?"], [href^="https://www.oboom.com/ad/"], [href^="https://www.popads.net/users/"], [href^="https://www.secureupload.eu/suprerefid="], [href^="https://www.share-online.biz/affiliate/"], [href^="https://www.spyoff.com/"], a[onmousedown^="this.href='/wp-content/embed-ad-content/"], a[onmousedown^="this.href='http://paid.outbrain.com/network/redir?"][target="_blank"], a[onmousedown^="this.href='http://staffpicks.outbrain.com/network/redir?"][target="_blank"], a[onmousedown^="this.href='https://paid.outbrain.com/network/redir?"][target="_blank"], a[style="display:block;width:300px;min-height:250px"][href^="http://li.cnet.com/click?"], a[target="_blank"][href^="http://api.taboola.com/"], a[target="_blank"][onmousedown="this.href^='http://paid.outbrain.com/network/redir?"], aside[id^="div-gpt-ad"], bottomadblock, div[class*="_AdInArticle_"], div[class^="Ad__adContainer"], div[class^="Ad__bigBox"], div[class^="Ad__container"], div[class^="BlockAdvert-"], div[class^="block-openx-"], div[class^="gemini-ad"], div[class^="local-feed-banner-ads"], div[class^="proadszone-"], div[id^="ADV-SLOT-"], div[id^="MarketGid"], div[id^="YFBMSN"], div[id^="acm-ad-tag-"], div[id^="ad-div-"], div[id^="ad-server-"], div[id^="ad_script_"], div[id^="adrotate_widgets-"], div[id^="ads120_600-widget"], div[id^="ads250_250-widget"], div[id^="ads300_100-widget"], div[id^="ads300_250-widget"], div[id^="ads300_600-widget"], div[id^="advads-"], div[id^="advads_"], div[id^="block-views-topheader-ad-block-"], div[id^="cns_ads_"], div[id^="crt-"][style], div[id^="dfp-ad-"], div[id^="dfp-slot-"], div[id^="div-adtech-ad-"], div[id^="div-gpt-ad"], div[id^="div_ad_stack_"], div[id^="div_openx_ad_"], div[id^="dmRosAdWrapper"], div[id^="google_ads_iframe_"], div[id^="google_dfp_"], div[id^="lazyad-"], div[id^="proadszone-"], div[id^="q1-adset-"], div[itemtype="http://schema.org/WPAdBlock"], div[itemtype="http://www.schema.org/WPAdBlock"], iframe[id^="google_ads_frame"], iframe[id^="google_ads_iframe"], iframe[src^="http://ad.yieldmanager.com/"], iframe[src^="http://cdn1.adexprt.com/"], iframe[src^="http://cdn2.adexprt.com/"], img[alt^="Fuckbook"], p[id^="div-gpt-ad-"], topadblock, [href^="http://duckcash.eu/"], [href^="http://www.cash-duck.com/"], [href^="http://www.coinducks.com/"], [href^="http://www.duckcash.eu/"], [href^="http://www.ducksnetwork.com/"], [href^="http://www.duckssolutions.com/"], [href^="http://www.fducks.com/"], [href^="http://www.moneyducks.com/"], [href^="http://www.richducks.com/"], input[onclick^="window.open('http://www.FriendlyDuck.com/"], input[onclick^="window.open('http://www.friendlyduck.com/"], a[href*=".trust.zone"], [onclick*="content.ad/"], [href^="http://internalredirect.site/"], [href^="http://rekoverr.com/"], AMP-AD, iframe[src^="http://static.mozo.com.au/strips/"], div[id^="mainads"], [href^="http://www.zergnet.com/i/"], div[id^="zergnet-widget"], a[href*="://3wr110.xyz/"], [href^="http://czasdzieci.pl/adurl"], [href^="http://rtb.4finance.com/click/"], [href^="http://wlbetathome.adsrv.eacdn.com"], div[onclick^="update_ad("], li[data-title="Sponsorowane"], [class*="coockie"], [class^="box-cookie"], [id*="ciasteczka_alert"], [id*="coockie"], [id^="cookies-message"], [id^="PolitykaPrywatnosci"], aside[class*="Cookie"], aside[class*="cookie"], ciasteczka:not(body):not(html), co15ie87a, cookidiv:not(body):not(html), div[class^="pea_cook_wrapper"], div[id^="cookemessage"], DIV[style*="background:url(images/cookies_tlo.png)"], DIV[style*="url(layout/cookies.png)"], iframe[class*="Cookie"], iframe[class*="cookie"], inpl_cp_cnt:not(body):not(html), nav[class*="Cookie"], nav[class*="cookie"], sliding-popup:not(body):not(html), span[class*="Cookie"], span[class*="cookie"], div[class*="cookie"], :not(input)[id*="cookie"], :not(input)[id*="Cookie"], [id*="cookie-"], [id*="cookie_"], div[class*="Cookie"], [id^="topInfo"], [class*="cookie-policy"]:not(body):not(html), a[href*=".adsrv.eacdn.com/"] > img, [href^="http://amzn.to/"] > img[src^="data"], div > [class][onclick*=".updateAnalyticsEvents"], td[valign="top"] > .mainmenu[style="padding:10px 0 0 0 !important;"]
{
    display: none !important;
}
```
