### ISSUE TITLE
cryptonews.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6139]
![2018-02-08-cryptonews pl bitcoin litecoin _ bitcoin informacje - news _ kryptowaluty](https://user-images.githubusercontent.com/5884000/35962047-36273d96-0cb0-11e8-9b4f-f33ce23ef6ad.png)

pusta sekcja polecamy

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
Za bardzo nie ma co tam wyciąć by się podniosło (może robią lukę by ją za niedługo zagospodarować reklamą boczną):

<ul>

```css
@media only screen and (min-width: 1200px)
.sidebar-right #sidebar {
     padding-top: 510px; 
}
```

</ul>

`cryptonews.pl###sidebar:style(padding-top: 0 !important)`
