### ISSUE TITLE
hbogo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7924]
Scrollowanie strony działa dopiero po odświeżeniu.

**Comment by krystian3w** [comment]
Coś wycięło RODO ale nie naprawiło przewijania:

Właściwości `<body>`:
```css
element.style {
    padding-right: 16px;
}
body.banner {
    overflow: hidden;
}
```

`hbogo.pl##body.banner:style(overflow: auto; padding-right: 0 !important;)`

Trzeba by ustalić co i przenieść pewnie na listę dla uBlock Origin / AdGuard.
