### ISSUE TITLE
http://www.polsatsport.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8146]
http://www.polsatsport.pl/wiadomosc/2018-06-24/ms-2018-senegal-japonia-relacja-i-wynik-na-zywo

![20180624-001-screenshot](https://user-images.githubusercontent.com/9846948/41821103-f6206fc8-77db-11e8-884a-7ef783f6282a.png)

```
polsatsport.pl###social-small
```

**Comment by hawkeye116477** [comment]
To jest tylko odnośnik do komentarzy, więc może lepiej to zostawić :smile:.

**Comment by krystian3w** [comment]
A może takie coś, nie testowałem jak działa w AdGuard ale daje radę w uBlock Origin.

```css
www.polsatsport.pl#$##social-small > .soc-koment { background: none; visibility: hidden; width: 300px  !important; height: 20px  !important; }
www.polsatsport.pl#$##social-small > .soc-koment:after { content: 'przejdź do sekcji komentarzy'; visibility: visible; display: block; }
```

```css
www.polsatsport.pl###social-small > .soc-koment:style(background: none; visibility: hidden; width: 300px !important; height: 20px !important;)
www.polsatsport.pl###social-small > .soc-koment:after:style(content: 'przejdź do sekcji komentarzy'; visibility: visible; display: block;)
```

---


```css
#social-small > .soc-koment {
  background: none;
  visibility: hidden;
  width: 300px;
  height: 20px;
}
#social-small > .soc-koment:after {
  content: 'przejdź do sekcji komentarzy';
  visibility: visible;
  display: block;
  padding: 5px;
}
```
