### ISSUE TITLE
paypal.com/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9398]
Pustka po cookies ( na dole ), da się coś z tym zrobić ?

**Comment by krystian3w** [comment]
Rozciągnięta stopka, ja bym zostawił, szkoda zachodu a jeszcze popsujemy coś na etapie po zalogowaniu.

**Comment by krystian3w** [comment]
```css
.gdprCookieBanner-acceptedAll {
    margin-bottom: 0;
}
```
